<!--<div data-mage-init='{"hello": {"message": "HELLO WORLD!"}}'>-->
<!--    Content HTML-->
<!--</div>-->
<p>This is test this is text this is text at the top.</p>
<div id="header">
    <p>This is the sticky thingy that is really cool.</p>
</div>
<p>This is test this is text this is text at the bottom.</p>
<script type="text/javascript">
    require(['sticky'], function () {
        $(window).load(function(){
            $("#header").sticky({ topSpacing: 0 });
        });
    });
</script>

<u> 2019 MDREAMS.COM.SG</u>